services:
  - type: web
    name: ayanfe-ai
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node render-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: PGDATABASE
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: BANK_ACCOUNT_NUMBER
        sync: false
      - key: BANK_NAME
        sync: false
      - key: BANK_ACCOUNT_NAME
        sync: false