services:
  - type: web
    name: ayanfe-ai
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node render-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: AROuRwAgEy7rclj8fw2pUhnaXMRqRdFu59y1aFkW0BuYKCPUURUgTbauXvwGcKpHT+g1mOIwG9gkzrMuMORr1w==
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_FBPhiksH10Ot@ep-purple-butterfly-a6w2lltn.us-west-2.aws.neon.tech/neondb?sslmode=require
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        value: sk_test_51RHkDvFRoFhvjQaQnNgxCZ6LBFB6SvoGyyDvUa5jfaqrkR6gbez8LUgfc5WQjEjVrhVT2LIUKHMfuInIZKEFq8s00063YoCu0g
      - key: VITE_STRIPE_PUBLIC_KEY
        value: pk_test_51RHkDvFRoFhvjQaQihs7ZHICUORST00ZZprC1F3fzFjkr3HXy0jBgr2YFHve5bF43yBywXl0WYwl9x6ZbbrVdiLR001lqO43Fk
      - key: PGDATABASE
        value: neondb
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: ADMIN_USERNAME
        value: akewusholaabdulbakri101
      - key: ADMIN_PASSWORD
        value: Makemoney@11
      - key: ADMIN_EMAIL
        value: akewusholaabdulbakri101@gmail.com
      - key: BANK_ACCOUNT_NUMBER
        value: 9019185241
      - key: BANK_NAME
        value: opay
      - key: BANK_ACCOUNT_NAME
        valud: Akewushola Abdulbakri temitope
